from enum import Enum


class LedgerEvent(str, Enum):
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    REQUEST_REJECTED_MALFORMED = "REQUEST_REJECTED_MALFORMED"
    REQUEST_ERRORED = "REQUEST_ERRORED"
    IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
    MANDATE_VERIFIED = "MANDATE_VERIFIED"
    MANDATE_REJECTED = "MANDATE_REJECTED"
    NONCE_CONSUMED = "NONCE_CONSUMED"
    NONCE_REPLAY_REJECTED = "NONCE_REPLAY_REJECTED"
    POLICY_VERDICT = "POLICY_VERDICT"
    STEP_UP_QUEUED = "STEP_UP_QUEUED"
    # Reserved now, written starting Phase 4 -- adding a new event type is
    # chain-safe (old rows are untouched); changing an existing type's
    # payload shape is not, so these are named ahead of time.
    STEP_UP_APPROVED = "STEP_UP_APPROVED"
    STEP_UP_REJECTED = "STEP_UP_REJECTED"
    SPEND_RESERVED = "SPEND_RESERVED"
    RAZORPAY_CALL = "RAZORPAY_CALL"
    EXECUTION_COMMITTED = "EXECUTION_COMMITTED"
    EXECUTION_DEDUPED = "EXECUTION_DEDUPED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
