"""Keyring: the control plane loads ONLY public keys. Private signing keys
never enter this process -- they live wherever the user/merchant sign from
(a script, the buyer agent, a wallet), generated by scripts/generate_keys.py.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from nacl.encoding import Base64Encoder
from nacl.exceptions import BadSignatureError
from nacl.signing import SigningKey, VerifyKey

from config import get_settings
from mandates.canonical import signing_bytes
from mandates.errors import MandateError, MandateErrorCode
from mandates.schemas import UnsignedCartMandate, UnsignedIntentMandate


class Keyring:
    """Resolves user_id -> public key and merchant_id -> public key.

    Built either from an in-memory mapping (tests) or from a directory laid
    out by scripts/generate_keys.py (the running service).
    """

    def __init__(
        self,
        user_keys: dict[str, VerifyKey],
        merchant_keys: dict[str, VerifyKey],
    ):
        self._user_keys = dict(user_keys)
        self._merchant_keys = dict(merchant_keys)

    @classmethod
    def from_dir(cls, path: Path) -> Keyring:
        """Loads {role}_ed25519.pub + {role}_ed25519.id pairs for role in
        (user, merchant). The .id sidecar makes the id<->key binding explicit
        and inspectable rather than implied by a naming convention.
        """
        user_id, user_key = cls._load_role(path, "user")
        merchant_id, merchant_key = cls._load_role(path, "merchant")
        return cls(user_keys={user_id: user_key}, merchant_keys={merchant_id: merchant_key})

    @staticmethod
    def _load_role(path: Path, role: str) -> tuple[str, VerifyKey]:
        pub_path = path / f"{role}_ed25519.pub"
        id_path = path / f"{role}_ed25519.id"
        if not pub_path.exists() or not id_path.exists():
            raise FileNotFoundError(
                f"missing {role} keyring files under {path} "
                f"(run scripts/generate_keys.py first)"
            )
        owner_id = id_path.read_text().strip()
        key_b64 = pub_path.read_text().strip()
        try:
            verify_key = VerifyKey(key_b64.encode("ascii"), encoder=Base64Encoder)
        except ValueError as exc:
            raise ValueError(f"invalid public key in {pub_path}: {exc}") from exc
        return owner_id, verify_key

    def user_key(self, user_id: str) -> VerifyKey:
        try:
            return self._user_keys[user_id]
        except KeyError:
            raise MandateError(
                MandateErrorCode.UNKNOWN_SIGNER, f"no registered user key for user_id={user_id!r}"
            ) from None

    def merchant_key(self, merchant_id: str) -> VerifyKey:
        try:
            return self._merchant_keys[merchant_id]
        except KeyError:
            raise MandateError(
                MandateErrorCode.UNKNOWN_SIGNER,
                f"no registered merchant key for merchant_id={merchant_id!r}",
            ) from None


@lru_cache
def get_keyring() -> Keyring:
    """The service's Keyring, loaded once from MANDATE_KEYRING_DIR."""
    return Keyring.from_dir(Path(get_settings().mandate_keyring_dir))


def sign_mandate(
    mandate: UnsignedIntentMandate | UnsignedCartMandate, signing_key: SigningKey
) -> str:
    """Returns the base64-encoded signature over `mandate`'s signing bytes."""
    signature = signing_key.sign(signing_bytes(mandate)).signature
    return Base64Encoder.encode(signature).decode("ascii")


def verify_signature(
    mandate: UnsignedIntentMandate | UnsignedCartMandate,
    signature_b64: str,
    key: VerifyKey,
    error_code: MandateErrorCode,
) -> None:
    """Raises MandateError(MALFORMED) on an undecodable signature, or
    MandateError(error_code) on a well-formed signature that doesn't verify.
    """
    try:
        signature = Base64Encoder.decode(signature_b64.encode("ascii"))
    except ValueError as exc:
        raise MandateError(MandateErrorCode.MALFORMED, f"signature is not valid base64: {exc}") from exc

    try:
        key.verify(signing_bytes(mandate), signature)
    except (BadSignatureError, ValueError) as exc:
        # ValueError covers e.g. a syntactically valid base64 string that
        # decodes to something other than 64 bytes.
        raise MandateError(error_code, f"signature verification failed: {exc}") from exc
